### ISSUE TITLE
Expected or unexpected behavior regarding model fit method 

### ISSUE THREAD

**Issue by engrut** [maciejkula/spotlight#107]
I am trying spotlight and noticed two things which I am not sure if they are expected outcome or behavior or not. 

Use case: 
A simplistic example is as follows:
```
user_ids : [1,2,3..............................]
item_ids = [1,2,3,......................]

interactions can look like this (userid, itemid):
(1,5), (2,3), (1,1), (9,2), etc etc 

```
Initially, I train the model on some historical data of user-item interactions. After that, each a user interacts with an item, I update the model by calling the fit method. 

Case 1: Calling fit repeatedly for ImplicitSequenceModel
[](https://github.com/maciejkula/spotlight/blob/master/spotlight/sequence/implicit.py)
`model.fit(sequences)`
Here I get the following error:

```
Traceback (most recent call last):
  File "spotlight_rec.py", line 110, in <module>
    main()
  File "spotlight_rec.py", line 80, in main
    rt_counter = recommender.train(train_set)
  File "spotlight_rec.py", line 38, in train
    self.model.fit(self.sequences)
  File "/opt/conda/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 215, in fit
    self._check_input(sequences)
  File "/opt/conda/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 192, in _check_input
    raise ValueError('Maximum item id greater '
ValueError: Maximum item id greater than number of items in model.

```
The error happens exactly at this point: 
```
def _check_input(self, item_ids):

        if isinstance(item_ids, int):
            item_id_max = item_ids
        else:
            item_id_max = item_ids.max()

        if item_id_max >= self._num_items:
            raise ValueError('Maximum item id greater '
                             'than number of items in model.')
```

This condition `(if item_id_max >= self._num_items)` can be true for us because a user could interact with an item which has an id number higher than the number of items. 

Our current workarount: To reinitialize when we encounter this error. 
Main question: Is it an expected behavior? and how can we handle this situation?

Case 2: Calling fit repeatedly or just one time for ImplicitFactorizationModel
In both these cases, I get an error with the `len(item_ids) % mini-batchsize` == 1. For example, if len(item_ids) is 17, and mini-batchsize is 8 then 17%8==1 leading to a value error. In my case, the mini-batchsize is 128. It happends at the last interation in creating user and item embedings in `forward` method of `BilinearNet` class. 

Value Error:
```
Traceback (most recent call last):
  File "src/spotlight_recommender.py", line 136, in <module>
    main()
  File "src/spotlight_recommender.py", line 114, in main
    recommender.train(train_set)
  File "src/spotlight_recommender.py", line 38, in train
    self.model.fit(data)
  File "/home/shoaib/anaconda3/lib/python3.5/site-packages/spotlight/factorization/implicit.py", line 233, in fit
    positive_prediction = self._net(user_var, item_var)
  File "/home/shoaib/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shoaib/anaconda3/lib/python3.5/site-packages/spotlight/factorization/representations.py", line 92, in forward
    dot = (user_embedding * item_embedding).sum(1)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```

The error occurs in the following code:
```
def forward(self, user_ids, item_ids):
        """
        Compute the forward pass of the representation.
        Parameters
        ----------
        user_ids: tensor
            Tensor of user indices.
        item_ids: tensor
            Tensor of item indices.
        Returns
        -------
        predictions: tensor
            Tensor of predictions.
        """

        user_embedding = self.user_embeddings(user_ids)
        item_embedding = self.item_embeddings(item_ids)

        user_embedding = user_embedding.squeeze()
        item_embedding = item_embedding.squeeze()

        user_bias = self.user_biases(user_ids).squeeze()
        item_bias = self.item_biases(item_ids).squeeze()

        dot = (user_embedding * item_embedding).sum(1)

        return dot + user_bias + item_bias
```
The error occurs when` len(item_ids) `is 1. It works for all the rest values. After some logging, it goes like this. 128, 128, 128....................,1 which causes an error. When len(item_ids) is 1, I also notice that item_embedding looks different too. 

Current work arrount: We just skip this iteration and retrain it in the next.
Main question: Are we doing something wrong if its an expected behavior? Why such situation can't be handled within this method? 

Extra:
Normal item embeding when the size is 128: 
```
[torch.FloatTensor of size 128x32]
 <class 'torch.autograd.variable.Variable'>
Variable containing:
-0.0585  0.1001  0.0464  ...   0.0846  0.1175 -0.1926
-0.0459  0.0973 -0.1781  ...   0.0870  0.0962 -0.1985
 0.1101  0.0706 -0.0717  ...   0.1948 -0.0446 -0.2401
          ...             ⋱             ...          
 0.1779  0.1666  0.1758  ...   0.1664  0.0789 -0.0398
 0.2808  0.2151  0.0562  ...   0.0679  0.0388  0.0283
-0.6652  0.6864 -0.8043  ...  -0.6818 -0.3306  0.4183
```

Last round when the size  is 1: 
```
[torch.FloatTensor of size 128x32]
 <class 'torch.autograd.variable.Variable'>
Variable containing:
 0.4371
 0.5031
-0.1965
 0.5416
 0.2742
-0.4299
 0.4275
 0.5921
-0.5964
-0.3495
-0.3941
 0.4900
 0.5652
-0.4823
 0.4789
 0.4647
-0.4036
 0.3759
-0.4495
 0.1618
 0.4748
-0.5056
-0.6162
-0.5277
-0.4750
 0.4905
-0.3921
 0.4476
 0.4825
-0.4493
 0.5846
-0.5344


```

**Comment by maciejkula** [comment]
That's a lot of questions :)

1. `ValueError: Maximum item id greater than number of items in model.` -> this is the desired behaviour. You initialize the model with N items, then try to train an embedding for more than N items, which is not going to work. You should initialize it with a larger N if you expect to be adding more items. Imagine you were using `sklearn`, and fitted a model with 10 features. What would you expect to happen if you called `partial_fit` again with 20 features? You also get `ValueError: Number of features 20 does not match previous data 10.`.
2. This is a bug related to use of `squeeze`: we should be squeezing dimensions other than the first.

Would you mind trying your hand at a fix for (2)? I imagine the following plan:
1. Add a test that blows up with the same symptom.
2. Change the squeeze code to pass the new test.

**Comment by engrut** [comment]
I realized it after finishing the post :)

1) Okay, initializing it with a way higher number resolved it. Another alternative way, was catch the exception and initialize the model. 

2) I can give it a try.

**Comment by maciejkula** [comment]
I think the problem is that we should only be squeezing the last dimension, not all of them. It would be great if you had a short example that shows this problem -- I could then relatively easily fix it.

**Comment by duynguyen158** [comment]
Hi there! I'm running into the same problem as (2) where, given the default batch size of 256, if my `Interactions` dataset has `n` interactions and `n % 256 == 1`, the `squeeze()` bug happens in the iteration where only 1 user ID and 1 item ID are passed into `BilinearNet.forward()`.

@maciejkula If you're still interested in and have time to fix, let me know how I can help! And many thanks for the library; it's been tremendously helpful to our organization.
