### ISSUE TITLE
Error when using Precision/Recall (ImplicitSequenceModel)

### ISSUE THREAD

**Issue by ajhepburn** [maciejkula/spotlight#149]
```
Traceback (most recent call last):
  File "model_spotlight.py", line 536, in <module>
    sim.run(defaults=True)
  File "model_spotlight.py", line 528, in run
    evaluation = self.evaluation(model, (train, test))
  File "model_spotlight.py", line 439, in evaluation
    train_prec, train_rec = sequence_precision_recall_score(model, train)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/evaluation.py", line 128, in sequence_precision_recall_score
    predictions = -model.predict(sequences[i])
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 318, in predict
    self._check_input(sequences)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 187, in _check_input
    item_id_max = item_ids.max()
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/numpy/core/_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity
```

I change my `Interactions` matrices to `SequenceInteractions` instances during cross validation. I think this may be because `SequenceInteractions` has no `item_ids` member?

**Comment by ajhepburn** [comment]
Just to add, I tried passing in the `item_ids` to line:
`predictions = -model.predict(sequences[i], item_ids[i])`
but no luck, same error.

**Comment by ajhepburn** [comment]
I've found where it breaks, it tries to call max on an array with no values in it:

```
2019-03-12 17:41:30,000 [MainThread  ] [INFO ]  Beginning model evaluation...
[[    0]
 [    1]
 [    2]
 ...
 [11436]
 [11437]
 [11438]]
[]
Traceback (most recent call last):
  File "model_spotlight.py", line 542, in <module>
    sim.run(defaults=True)
  File "model_spotlight.py", line 534, in run
    evaluation = self.evaluation(model, (train, test), (train_ids, item_ids))
  File "model_spotlight.py", line 444, in evaluation
    prec = sequence_precision_recall_score(model, test)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/evaluation.py", line 128, in sequence_precision_recall_score
    predictions = -model.predict(sequences[i])
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 303, in predict
    self._check_input(sequences)
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/spotlight/sequence/implicit.py", line 179, in _check_input
    item_id_max = item_ids.max()
  File "/home/alex/anaconda3/envs/recsys/lib/python3.6/site-packages/numpy/core/_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Is there maybe something wrong with the formatting of the item_ids that there is a sequence where there are no item IDs?
