### ISSUE TITLE
load own dataset

### ISSUE THREAD

**Issue by juanremi** [maciejkula/spotlight#30]
Hi, i have a dataset in a cvs format (https://raw.githubusercontent.com/juanremi/datasets-to-CF-recsys/master/bigquery-frutas-sin-items-no-vistos-ids.csv), the first row are the headers (user, item, rating).

So i modify the file https://raw.githubusercontent.com/maciejkula/spotlight/master/spotlight/datasets/movielens.py to load my own dataset:
`import os
import torch
import numpy as np

from spotlight.datasets import _transport
from spotlight.interactions import Interactions

URL_PREFIX = ('http://localhost/juanbits/pruebas/datasets/myheaders')

def _get_my_own(dataset):
    extension = '.csv'
    URL_PREFIX = '/home/user/htdocs/pruebas/datasets/myheaders/'

    data = np.genfromtxt(URL_PREFIX + dataset + extension, delimiter=',', names=True, dtype=(int, int, float))
    usuarios = data['user']
    items = data['item']
    ratings = data['rating']
    return (usuarios, items, ratings)

def get_my_own_dataset(myfile):
    """
    Returns
    -------

    Interactions: :class:`spotlight.interactions.Interactions`
        instance of the interactions class
    """

    url = myfile

    return Interactions(*_get_my_own(url))

dataset = get_my_own_dataset('bigquery-frutas-sin-items-no-vistos-ids')
print(dataset)

from spotlight.factorization.explicit import ExplicitFactorizationModel

model = ExplicitFactorizationModel(loss='regression',
                                   embedding_dim=128,  # latent dimensionality
                                   n_iter=10,  # number of epochs of training
                                   batch_size=1024,  # minibatch size
                                   l2=1e-9,  # strength of L2 regularization
                                   learning_rate=1e-3,
                                   use_cuda=torch.cuda.is_available())

from spotlight.cross_validation import random_train_test_split

train, test = random_train_test_split(dataset, random_state=np.random.RandomState(42))

print('Split into \n {} and \n {}.'.format(train, test))

model.fit(train, verbose=True)`

but when i run the output is:
`<Interactions dataset (14 users x 17 items x 139 interactions)>
Split into 
 <Interactions dataset (14 users x 17 items x 111 interactions)> and 
 <Interactions dataset (14 users x 17 items x 28 interactions)>.
Traceback (most recent call last):
  File "condadata.py", line 52, in <module>
    model.fit(train, verbose=True)
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/spotlight/factorization/explicit.py", line 172, in fit
    loss = loss_fnc(ratings_var, predictions)
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/spotlight/losses.py", line 191, in regression_loss
    return ((observed_ratings - predicted_ratings) ** 2).mean()
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/torch/autograd/variable.py", line 752, in __sub__
    return self.sub(other)
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/torch/autograd/variable.py", line 296, in sub
    return self._sub(other, False)
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/torch/autograd/variable.py", line 290, in _sub
    return Sub(inplace=inplace)(self, other)
  File "/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/torch/autograd/_functions/basic_ops.py", line 34, in forward
    return a.sub(b)
TypeError: sub received an invalid combination of arguments - got (torch.FloatTensor), but expected one of:
 * (float value)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (torch.DoubleTensor other)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor)
 * (float value, torch.DoubleTensor other)
`

any idea?

**Comment by maciejkula** [comment]
This is because the `ratings` attribute of your dataset has type `np.float64` instead of `np.float32`.

I can offer two suggestions:
- convert the ratings to `float32`: `dataset.ratings = dataset.ratings.astype(np.float32)`
- use the latest master branch of Spotlight that includes automatic datatype conversions.

**Comment by juanremi** [comment]
well I install some hours ago the spotlight lib on conda, versión 0.1.1, this no is the latest?

**Comment by maciejkula** [comment]
It is the latest release, but the master version here on Github has some new improvements.

**Comment by juanremi** [comment]
nice, i uninstall spotlight, clone the sporlight git and then i run the setup.py, but i dont know what are the opcions to complete these:
`python setup.py 
/var/www/miniconda2/envs/conda1/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py:331: UserWarning: Normalizing 'v0.1.1' to '0.1.1'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied`

**Comment by juanremi** [comment]
i uninstall spotlight, clone the github repository ans install it again, but i get the same error

**Comment by maciejkula** [comment]
Go into the cloned directory and run `pip install .`: this should work.

**Comment by juanremi** [comment]
why when i use model.predict(id_user) i got this error:
```
Traceback (most recent call last):
  File "conda1.py", line 69, in <module>
    print model.predict(1)
TypeError: predict() takes exactly 3 arguments (2 given)
```

**Comment by maciejkula** [comment]
I'm afraid the predict API here is a little wonky at the moment. Fixes are in the works but not ready to be merged yet.

For now, please pass in an array of user ids and items. For example, if you want to make predictions for user 1 for items 1, 2, and 3, try:
```python
predictions = model.predict(np.array([1, 1, 1], dtype=np.int64, np.array[1, 2, 3], dtype=np.int64)
```

**Comment by juanremi** [comment]
dont be afraid, we love your work :heart: 

i try that, and now i get the next error:
```
predictions = model.predict(np.array[1, 1, 1], dtype=np.int64, np.array[1, 2, 3], dtype=np.int64)
SyntaxError: non-keyword arg after keyword arg
```

**Comment by maciejkula** [comment]
Syntax problem, amended my answer above.

**Comment by juanremi** [comment]
oh i see:
`predictions = model.predict(np.array([1, 1, 1], dtype=np.int64), np.array([1, 2, 3], dtype=np.int64))`

**Comment by maciejkula** [comment]
I include some of the predict API fixes in this branch: https://github.com/maciejkula/spotlight/pull/31

You can give that a try as well.

**Comment by juanremi** [comment]
I'm only get this:
`[ 0.02556127 0.03148273 0.02408132]`

Is the score?, the item_id's are missing? thanks

**Comment by maciejkula** [comment]
Yes, these are the scores corresponding to your inputs.

**Comment by juanremi** [comment]
but when i try with this:

```
INPUT: 
predictions = model.predict(1)
OUTPUT:
[ 0.01160015  0.02628824  0.02972064  0.02319316  0.02643632  0.03024803
  0.02928654  0.03212331  0.03058725  0.02894426  0.02387976  0.0281925
  0.03137119  0.03292302  0.02974606  0.0244297   0.0088104 ]
```
i get the same, only get the "score", but the item_id's are missing and i cant know what item_id is for each score

**Comment by maciejkula** [comment]
These will be arranged from 0 to however many items you have.

**Comment by juanremi** [comment]
i have a dataset (user/item/rating) where the rating value would be only 0 or 1, whick model is the best for that. because I try use the ImplicitFactorizationModel, but i dont know why the predicted score no is between 0 or 1, sometimes the score is grather than 10 or lower as -6....

**Comment by maciejkula** [comment]
The [`ImplicitFactorizationModel`](https://maciejkula.github.io/spotlight/factorization/implicit.html#spotlight.factorization.implicit.ImplicitFactorizationModel) is probably the right choice.

The predicted scores only make sense as defining a ranking over products. You can have a look at my StackOverflow answer [here](https://stackoverflow.com/questions/41902860/interpreting-results-from-lightfm/45467232#45467232).

**Comment by juanremi** [comment]
but i see sometimes the models consider the "0" value as "unseen item", but in my case the 1=like and 0=unlike, 0 != "unseen", this may affect the results.

so i dont know how can I model my data if i dont have the item_ids("unseen items") for each user, only have the "liked and unliked" ids, and if this would be predicted using spotlight

:thinking:

**Comment by maciejkula** [comment]
If you believe that the important part of the signal is likes, and dislikes, you should use the explicit model. Then, the predicted scores should be roughly between 0 and 1.

However, chances are that the more important pattern in your dataset is revealed as the contrast between what the user liked and what they have not rated at all (that is, all the item ids they don't have likes for). In this case, you should use the implicit model, and only include user-item pairs where a like was observed. You may find [this](https://www.researchgate.net/profile/Yifan_Hu/publication/220765111_Collaborative_Filtering_for_Implicit_Feedback_Datasets/links/0912f509c579ddd954000000.pdf) reference paper useful.

I am reasonably confident that the vast majority of real-world recommender systems use implicit feeback.

**Comment by juanremi** [comment]
I run the experiment with ExplicitModel, and now i got a score between 0.55340898 (min) and 1.06373000 (max).
I try to understand, this is a probability. But why if the like=1 and dislike=0, why i get these values?.

what happens if i need make a decision and say if the score = LIKE or UNLIKE
My idea is:
```
mean = (min+max)/2
IF score > mean:
   LIKE
ELSE:
  UNLIKE
```

Can You give me a better idea?

Pd. I'm going to read the paper, thanks for all your support :1st_place_medal:

**Comment by juanremi** [comment]
With the probabilities of the experiment with ExplicitModel, if i get the values between 0.55340898 (min) and 1.06373000 (max), how can i fix the probabilities to be in the range 0 and 1 and no > 1, if the value of like=1 and dislike=0

the value that i get, is the probability the user "like" an item, but why this value is > 1. i dont understand if the real value is 0 or 1, and i think the probability should be in the range of 0 or 1, no > 1

:thinking:

**Comment by maciejkula** [comment]
Explicit feedback models do not output a probability. They merely try to approximate the ratings you give them. Because in your case they are between 1 and 0, the resulting scores could be confused with probabilities.

Implicit feedback models do not in general output probabilities either.

It is very uncommon to make a classification-like decision. The scores out of the models are instead used to order the items in descending order of the score, and return to the user some items from the head of the ranking.

**Comment by juanremi** [comment]
so... if the given values are 0 and 1, why the approximate ratings in this case are
aprox.Rating > 0.5
aprox.Rating > 1
and never tend to 0, all tend to 1 or are > 1

why the approximate ratings not are bewteen 0 and 1, and never they tend to 0

**Comment by maciejkula** [comment]
Machine learning models can be sensitive to your choice of hyperparameters. I would suggest playing with different hyperparameters and models until you get a better result. Have you had a look at the explicit feedback [evaluation function](https://maciejkula.github.io/spotlight/evaluation.html#spotlight.evaluation.rmse_score)? Did you read the explicit model [example](https://github.com/maciejkula/spotlight/tree/master/examples/movielens_explicit)?

**Comment by juanremi** [comment]
Yes I read de example, in fact I rely on that to do my experiment.

Yes i play with the hyperparameters, and this giveme the better results, RMSE=0.783811

```
model = ExplicitFactorizationModel(loss='poisson',
                                   embedding_dim=256,  # latent dimensionality
                                   n_iter=1,  # number of epochs of training
                                   batch_size=1024,  # minibatch size
                                   l2=1e-9,  # strength of L2 regularization
                                   learning_rate=1e-5,
                                   use_cuda=torch.cuda.is_available())
```
But I do not know what else I can do to improve the result :cry:

**Comment by maciejkula** [comment]
You should perform a thorough hyperparameter search. You could use `sklearn`'s [`ParameterSampler`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ParameterSampler.html), for example.

In particular, I would suggest (1) a higher learning rate, and (2) more iterations, (3) the regression loss as a baseline. If you haven't done so already, I would also suggest reading up on backpropagation/stochastic gradient descent: Spotlight's models are fitted using backpropagation, and some background knowledge will give you valuable intuition on what is going on.

**Comment by juanremi** [comment]
the dataset is: 100015 user/item/rating. the rating could be 0 or 1

---other problem---
is possible have a matrix:
user/item/rating/category/otherVar/similarity

*similarity is a value between 0 to 1. ex: .01, .95, .56
to:
1. recommend items by similarity (just similarity order DESC) WHERE category='category1' and otherVar='var1' and similatiry>n
2. recommend items with the value predicted but WHERE:
- category='category1' and otherVar='var2'
- category='category3'
3. recommend items using the cases described before, but excluding:
 - some category.. as WHERE category NOT IN 'category3, category2'
 - some items.. as WHERE items NOT IN (items, ids)

thanks

**Comment by maciejkula** [comment]
'Ratings' of 0 and 1 suggest that you actually have an _implicit_ feedback problem. If you continue using an explicit model, make sure you include both the 1s and the 0s in your ratings. If you choose an implicit model, make sure to include only the 1s.

As for your second question: absolutely. You just need to write some business logic code to implement that. It should be quite simple.

**Comment by juanremi** [comment]
well the ratings "are explicit", they mean like=1/unlike=0... maybe we need to change the values to:
like= 2
unlike= 1
?

im working to write the logic and i will be able to share it with you, i think this could be more stronger "spotlight"

**Comment by juanremi** [comment]
@maciejkula do you know (can help me please).. how can I reproduce https://github.com/maciejkula/spotlight with pytorch?

**Comment by maciejkula** [comment]
Spotlight uses PyTorch, so it's already there!

**Comment by juanremi** [comment]
@maciejkula lol i did a mistake... the link is https://getstream.io/blog/factorization-machines-recommendation-systems/ (to add to the triplets another dimension, like: category)

**Comment by vjjeffin** [comment]
Hi. I am getting the following error when i am trying to predict multiple Id's. predicting one by one is fine.

**predictions = model.predict(np.array([1, 1, 1], dtype=np.int64), np.array([0, 1, 2], dtype=np.int64))**
**RuntimeError: number of dims don't match in permute**


this is the complete code:
from spotlight.cross_validation import random_train_test_split

from spotlight.datasets.movielens import get_movielens_dataset
from spotlight.evaluation import rmse_score
from spotlight.factorization.explicit import ExplicitFactorizationModel
import numpy as np
dataset = get_movielens_dataset(variant='100K')

train, test = random_train_test_split(dataset)

model = ExplicitFactorizationModel(n_iter=1)
model.fit(train)

rmse = rmse_score(model, test)

rr=model.predict(1, item_ids=None)

**predictions = model.predict(np.array([1, 1, 1], dtype=np.int64), np.array([0, 1, 2], dtype=np.int64))**
