### ISSUE TITLE
Loading movielens dataset does not work

### ISSUE THREAD

**Issue by jfpuget** [maciejkula/spotlight#43]
This url is non existent: https://github.com/maciejkula/recommender_datasets/releases/download/

**Comment by maciejkula** [comment]
All of the download links [here](https://github.com/maciejkula/recommender_datasets/releases/) should work.

In particular, this address: https://github.com/maciejkula/recommender_datasets/releases/download/0.1.0/movielens_100K.hdf5 does work.

Could you give me a bit more detail of when Spotlight is trying to download from the URL you linked?

**Comment by jfpuget** [comment]
I tried the first example on your main page: https://github.com/maciejkula/spotlight
It could not load the movielens dataset.

Will try again when current install (I switched computer) is complete.

**Comment by maciejkula** [comment]
Can you please post the stack trace?

**Comment by jfpuget** [comment]
It works now.  I can't go back to the install that was failing, sorry for the noise.

**Comment by maciejkula** [comment]
Great, and thanks for the report! It's always good to flag problems even if sometimes they are false positives.

**Comment by pavanAlluri** [comment]
Hi @maciejkula, 

i have encountered the above error of unable to download `movielens_100k` from `example.py` of `bloom_embeddings`

Complete error reference:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-caa8df7efe1c>", line 1, in <module>
    dataset = get_movielens_dataset(variant='100K')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\movielens.py", line 70, in get_movielens_dataset
    return Interactions(*_get_movielens(url))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\movielens.py", line 37, in _get_movielens
    extension))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\_transport.py", line 36, in get_data
    download(url, dest_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\_transport.py", line 19, in download
    req.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/maciejkula/recommender_datasets/releases/download/v0.2.0%5Cmovielens_100K.hdf5
```

During my debug of the link reference i found that this line of code : `requests.get(url, stream=True)` in `_transport.py` of source code is where the error is originating from.

The url passed appears to be correct but somehow `requests.get` gets back with 404. So i downloaded the file manually placed in the destination folder & the i came across below error, which beyond my comprehension :)

```
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
<Interactions dataset (944 users x 1683 items x 100000 interactions)>
Traceback (most recent call last):
  File "C:/BNPP/recoEngine/example.py", line 339, in <module>
    random_state=random_state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\cross_validation.py", line 146, in user_based_train_test_split
    seed = random_state.randint(minint, maxint)
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32
```
Would appreciate your help in smoothly testing out the examples in spotlight.

Thanks,
Pavan
