### ISSUE TITLE
Troubleshooting example.py in bloom_embeddings

### ISSUE THREAD

**Issue by pavanAlluri** [maciejkula/spotlight#95]
Hi @maciejkula,

i have encountered errors of unable to download `movielens_100k` & `out of bounds for int32` from `example.py` of `bloom_embeddings`

Complete error reference:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-caa8df7efe1c>", line 1, in <module>
    dataset = get_movielens_dataset(variant='100K')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\movielens.py", line 70, in get_movielens_dataset
    return Interactions(*_get_movielens(url))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\movielens.py", line 37, in _get_movielens
    extension))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\_transport.py", line 36, in get_data
    download(url, dest_path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\datasets\_transport.py", line 19, in download
    req.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/maciejkula/recommender_datasets/releases/download/v0.2.0%5Cmovielens_100K.hdf5
```
During my debug of the link reference i found that this line of code : `requests.get(url, stream=True)` in `_transport.py` of source code is where the error is originating from.

The url passed appears to be correct but somehow requests.get gets back with `404`. So i downloaded the file manually and placed it in the destination folder & then i came across below error, which is beyond my comprehension :)

```
C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
<Interactions dataset (944 users x 1683 items x 100000 interactions)>
Traceback (most recent call last):
  File "C:/BNPP/recoEngine/example.py", line 339, in <module>
    random_state=random_state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\cross_validation.py", line 146, in user_based_train_test_split
    seed = random_state.randint(minint, maxint)
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32
```
Would appreciate your help in smoothly testing out the examples in spotlight.

Thanks,
Pavan

**Comment by pavanAlluri** [comment]
Just for reference, mentioning on how got to workaround the second error mentioned above & also one more which might have arose due to the workaround. Please do let me know if below changes makes sense.

In `cross_validation.py` changed the `maxint` value to `1234567890`. So that out of bounds error does not persist.

This change might have led me to:
```
Traceback (most recent call last):
  File "C:/BNPP/recoEngine/example.py", line 367, in <module>
    run(experiment_name, train, test, validation, random_state)
  File "C:/BNPP/recoEngine/example.py", line 261, in run
    validation)
  File "C:/BNPP/recoEngine/example.py", line 209, in evaluate_model
    model.fit(train, verbose=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\sequence\implicit.py", line 238, in fit
    user_representation)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\sequence\implicit.py", line 269, in _get_negative_prediction
    negative_prediction = self._net(user_representation, negative_var)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spotlight\sequence\representations.py", line 249, in forward
    target_embedding = (self.item_embeddings(targets)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 103, in forward
    self.scale_grad_by_freq, self.sparse
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\_functions\thnn\sparse.py", line 59, in forward
    output = torch.index_select(weight, 0, indices.view(-1))
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, !torch.cuda.IntTensor!), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
```
made one more change was made to source code to run `example.py`.
In `implicit.py`, class `ImplicitSequenceModel`, in function `_get_negative_prediction` changed the tensor 

`negative_var = Variable(gpu(torch.from_numpy(negative_items), self._use_cuda))` to
`negative_var = Variable(gpu(torch.LongTensor(negative_items), self._use_cuda))`

With these workarounds was able to get the `example.py` executed successfully.

Regards,
Pavan

**Comment by maciejkula** [comment]
Hi @pavanAlluri, both issues should be fixed in the master version of Spotlight.

Can you pull master and check that it works?

**Comment by pavanAlluri** [comment]
yeah its resolved, thank you
